'''

[{
    'Enabled': True,
    'Info': {
        'Name': 'eth0',
        'HwAddress': '00:12:15:78:55:bb',
        'MTU': 1500
    },
    'Link': {
        'AdminSettings': {
            'AutoNegotiation': False,
            'Speed': 10,
            'Duplex': 'Full'
        },
        'OperSettings': {
            'AutoNegotiation': False,
            'Speed': 10,
            'Duplex': 'Full'
        },
        'InterfaceType': 0
    },
    'IPv4': {
        'Enabled': True,
        'Config': {
            'Manual': [
                {
                    'Address': '192.168.1.101',
                    'PrefixLength': 24
                }
            ],
            'LinkLocal': None,
            'FromDHCP': None,
            'DHCP': False,
            '_value_1': None,
            '_attr_1': None
        }
    },
    'IPv6': None,
    'Extension': None,
    'token': 'eth0',
    '_attr_1': {
}
}]

{
    'InterfaceToken': 'eth0',
    'NetworkInterface': None
}




   [ONVIF_FRONT][ERROR]:




   Ошибка при смене IP через ONVIF: No element 'NetworkInterfaceSetConfiguration' in namespace 
   http://www.onvif.org/ver10/device/wsdl. 
   Available elements are: 
   {http://www.onvif.org/ver10/device/wsdl}GetServices, 
   {http://www.onvif.org/ver10/device/wsdl}GetServicesResponse, 
   {http://www.onvif.org/ver10/device/wsdl}GetServiceCapabilities, 
   {http://www.onvif.org/ver10/device/wsdl}GetServiceCapabilitiesResponse, 
   {http://www.onvif.org/ver10/device/wsdl}Capabilities, 
   {http://www.onvif.org/ver10/device/wsdl}GetDeviceInformation, 
   {http://www.onvif.org/ver10/device/wsdl}GetDeviceInformationResponse, 
   {http://www.onvif.org/ver10/device/wsdl}SetSystemDateAndTime, 
   {http://www.onvif.org/ver10/device/wsdl}SetSystemDateAndTimeResponse, 
   {http://www.onvif.org/ver10/device/wsdl}GetSystemDateAndTime, 
   {http://www.onvif.org/ver10/device/wsdl}GetSystemDateAndTimeResponse, 
   {http://www.onvif.org/ver10/device/wsdl}SetSystemFactoryDefault, 
   {http://www.onvif.org/ver10/device/wsdl}SetSystemFactoryDefaultResponse, 
   {http://www.onvif.org/ver10/device/wsdl}UpgradeSystemFirmware, 
   {http://www.onvif.org/ver10/device/wsdl}UpgradeSystemFirmwareResponse, 
   {http://www.onvif.org/ver10/device/wsdl}SystemReboot, 
   {http://www.onvif.org/ver10/device/wsdl}SystemRebootResponse, 
   {http://www.onvif.org/ver10/device/wsdl}RestoreSystem, 
   {http://www.onvif.org/ver10/device/wsdl}RestoreSystemResponse, 
   {http://www.onvif.org/ver10/device/wsdl}GetSystemBackup, 
   {http://www.onvif.org/ver10/device/wsdl}GetSystemBackupResponse, 
   {http://www.onvif.org/ver10/device/wsdl}GetSystemSupportInformation, 
   {http://www.onvif.org/ver10/device/wsdl}GetSystemSupportInformationResponse, 
   {http://www.onvif.org/ver10/device/wsdl}GetSystemLog, 
   {http://www.onvif.org/ver10/device/wsdl}GetSystemLogResponse, 
   {http://www.onvif.org/ver10/device/wsdl}GetScopes, 
   {http://www.onvif.org/ver10/device/wsdl}GetScopesResponse, 
   {http://www.onvif.org/ver10/device/wsdl}SetScopes, 
   {http://www.onvif.org/ver10/device/wsdl}SetScopesResponse, 
   {http://www.onvif.org/ver10/device/wsdl}AddScopes, 
   {http://www.onvif.org/ver10/device/wsdl}AddScopesResponse, 
   {http://www.onvif.org/ver10/device/wsdl}RemoveScopes, 
   {http://www.onvif.org/ver10/device/wsdl}RemoveScopesResponse, 
   {http://www.onvif.org/ver10/device/wsdl}GetDiscoveryMode, 
   {http://www.onvif.org/ver10/device/wsdl}GetDiscoveryModeResponse, 
   {http://www.onvif.org/ver10/device/wsdl}SetDiscoveryMode, 
   {http://www.onvif.org/ver10/device/wsdl}SetDiscoveryModeResponse, 
   {http://www.onvif.org/ver10/device/wsdl}GetRemoteDiscoveryMode, 
   {http://www.onvif.org/ver10/device/wsdl}GetRemoteDiscoveryModeResponse, 
   {http://www.onvif.org/ver10/device/wsdl}SetRemoteDiscoveryMode, 
   {http://www.onvif.org/ver10/device/wsdl}SetRemoteDiscoveryModeResponse, 
   {http://www.onvif.org/ver10/device/wsdl}GetDPAddresses, 
   {http://www.onvif.org/ver10/device/wsdl}GetDPAddressesResponse, 
   {http://www.onvif.org/ver10/device/wsdl}SetDPAddresses, 
   {http://www.onvif.org/ver10/device/wsdl}SetDPAddressesResponse, 
   {http://www.onvif.org/ver10/device/wsdl}GetEndpointReference, 
   {http://www.onvif.org/ver10/device/wsdl}GetEndpointReferenceResponse, 
   {http://www.onvif.org/ver10/device/wsdl}GetRemoteUser, 
   {http://www.onvif.org/ver10/device/wsdl}GetRemoteUserResponse, 
   {http://www.onvif.org/ver10/device/wsdl}SetRemoteUser, 
   {http://www.onvif.org/ver10/device/wsdl}SetRemoteUserResponse, 
   {http://www.onvif.org/ver10/device/wsdl}GetUsers, 
   {http://www.onvif.org/ver10/device/wsdl}GetUsersResponse, 
   {http://www.onvif.org/ver10/device/wsdl}CreateUsers, 
   {http://www.onvif.org/ver10/device/wsdl}CreateUsersResponse, 
   {http://www.onvif.org/ver10/device/wsdl}DeleteUsers, 
   {http://www.onvif.org/ver10/device/wsdl}DeleteUsersResponse, 
   {http://www.onvif.org/ver10/device/wsdl}SetUser, 
   {http://www.onvif.org/ver10/device/wsdl}SetUserResponse, 
   {http://www.onvif.org/ver10/device/wsdl}GetWsdlUrl, 
   {http://www.onvif.org/ver10/device/wsdl}GetWsdlUrlResponse, 
   {http://www.onvif.org/ver10/device/wsdl}GetCapabilities, 
   {http://www.onvif.org/ver10/device/wsdl}GetCapabilitiesResponse, 
   {http://www.onvif.org/ver10/device/wsdl}GetHostname, 
   {http://www.onvif.org/ver10/device/wsdl}GetHostnameResponse, 
   {http://www.onvif.org/ver10/device/wsdl}SetHostname, 
   {http://www.onvif.org/ver10/device/wsdl}SetHostnameResponse, 
   {http://www.onvif.org/ver10/device/wsdl}SetHostnameFromDHCP, 
   {http://www.onvif.org/ver10/device/wsdl}SetHostnameFromDHCPResponse, 
   {http://www.onvif.org/ver10/device/wsdl}GetDNS, 
   {http://www.onvif.org/ver10/device/wsdl}GetDNSResponse, 
   {http://www.onvif.org/ver10/device/wsdl}SetDNS, 
   {http://www.onvif.org/ver10/device/wsdl}SetDNSResponse, 
   {http://www.onvif.org/ver10/device/wsdl}GetNTP, 
   {http://www.onvif.org/ver10/device/wsdl}GetNTPResponse, 
   {http://www.onvif.org/ver10/device/wsdl}SetNTP, 
   {http://www.onvif.org/ver10/device/wsdl}SetNTPResponse, 
   {http://www.onvif.org/ver10/device/wsdl}GetDynamicDNS, 
   {http://www.onvif.org/ver10/device/wsdl}GetDynamicDNSResponse, 
   {http://www.onvif.org/ver10/device/wsdl}SetDynamicDNS, 
   {http://www.onvif.org/ver10/device/wsdl}SetDynamicDNSResponse, 
   {http://www.onvif.org/ver10/device/wsdl}GetNetworkInterfaces, 
   {http://www.onvif.org/ver10/device/wsdl}GetNetworkInterfacesResponse, 
   {http://www.onvif.org/ver10/device/wsdl}SetNetworkInterfaces, 
   {http://www.onvif.org/ver10/device/wsdl}SetNetworkInterfacesResponse, 
   {http://www.onvif.org/ver10/device/wsdl}GetNetworkProtocols, 
   {http://www.onvif.org/ver10/device/wsdl}GetNetworkProtocolsResponse, 
   {http://www.onvif.org/ver10/device/wsdl}SetNetworkProtocols, 
   {http://www.onvif.org/ver10/device/wsdl}SetNetworkProtocolsResponse, 
   {http://www.onvif.org/ver10/device/wsdl}GetNetworkDefaultGateway, 
   {http://www.onvif.org/ver10/device/wsdl}GetNetworkDefaultGatewayResponse, 
   {http://www.onvif.org/ver10/device/wsdl}SetNetworkDefaultGateway, 
   {http://www.onvif.org/ver10/device/wsdl}SetNetworkDefaultGatewayResponse, 
   {http://www.onvif.org/ver10/device/wsdl}GetZeroConfiguration, 
   {http://www.onvif.org/ver10/device/wsdl}GetZeroConfigurationResponse, 
   {http://www.onvif.org/ver10/device/wsdl}SetZeroConfiguration, 
   {http://www.onvif.org/ver10/device/wsdl}SetZeroConfigurationResponse, 
   {http://www.onvif.org/ver10/device/wsdl}GetIPAddressFilter, 
   {http://www.onvif.org/ver10/device/wsdl}GetIPAddressFilterResponse, 
   {http://www.onvif.org/ver10/device/wsdl}SetIPAddressFilter, 
   {http://www.onvif.org/ver10/device/wsdl}SetIPAddressFilterResponse, 
   {http://www.onvif.org/ver10/device/wsdl}AddIPAddressFilter, 
   {http://www.onvif.org/ver10/device/wsdl}AddIPAddressFilterResponse, 
   {http://www.onvif.org/ver10/device/wsdl}RemoveIPAddressFilter, 
   {http://www.onvif.org/ver10/device/wsdl}RemoveIPAddressFilterResponse, 
   {http://www.onvif.org/ver10/device/wsdl}GetAccessPolicy, 
   {http://www.onvif.org/ver10/device/wsdl}GetAccessPolicyResponse, 
   {http://www.onvif.org/ver10/device/wsdl}SetAccessPolicy, 
   {http://www.onvif.org/ver10/device/wsdl}SetAccessPolicyResponse, 
   {http://www.onvif.org/ver10/device/wsdl}CreateCertificate, 
   {http://www.onvif.org/ver10/device/wsdl}CreateCertificateResponse, 
   {http://www.onvif.org/ver10/device/wsdl}GetCertificates, 
   {http://www.onvif.org/ver10/device/wsdl}GetCertificatesResponse, 
   {http://www.onvif.org/ver10/device/wsdl}GetCertificatesStatus, 
   {http://www.onvif.org/ver10/device/wsdl}GetCertificatesStatusResponse, 
   {http://www.onvif.org/ver10/device/wsdl}SetCertificatesStatus, 
   {http://www.onvif.org/ver10/device/wsdl}SetCertificatesStatusResponse, 
   {http://www.onvif.org/ver10/device/wsdl}DeleteCertificates, 
   {http://www.onvif.org/ver10/device/wsdl}DeleteCertificatesResponse, 
   {http://www.onvif.org/ver10/device/wsdl}GetPkcs10Request, 
   {http://www.onvif.org/ver10/device/wsdl}GetPkcs10RequestResponse, 
   {http://www.onvif.org/ver10/device/wsdl}LoadCertificates, 
   {http://www.onvif.org/ver10/device/wsdl}LoadCertificatesResponse, 
   {http://www.onvif.org/ver10/device/wsdl}GetClientCertificateMode, 
   {http://www.onvif.org/ver10/device/wsdl}GetClientCertificateModeResponse, 
   {http://www.onvif.org/ver10/device/wsdl}SetClientCertificateMode, 
   {http://www.onvif.org/ver10/device/wsdl}SetClientCertificateModeResponse, 
   {http://www.onvif.org/ver10/device/wsdl}GetCACertificates, 
   {http://www.onvif.org/ver10/device/wsdl}GetCACertificatesResponse, 
   {http://www.onvif.org/ver10/device/wsdl}LoadCertificateWithPrivateKey, 
   {http://www.onvif.org/ver10/device/wsdl}LoadCertificateWithPrivateKeyResponse, 
   {http://www.onvif.org/ver10/device/wsdl}GetCertificateInformation, 
   {http://www.onvif.org/ver10/device/wsdl}GetCertificateInformationResponse, 
   {http://www.onvif.org/ver10/device/wsdl}LoadCACertificates, 
   {http://www.onvif.org/ver10/device/wsdl}LoadCACertificatesResponse, 
   {http://www.onvif.org/ver10/device/wsdl}CreateDot1XConfiguration, 
   {http://www.onvif.org/ver10/device/wsdl}CreateDot1XConfigurationResponse, 
   {http://www.onvif.org/ver10/device/wsdl}SetDot1XConfiguration, 
   {http://www.onvif.org/ver10/device/wsdl}SetDot1XConfigurationResponse, 
   {http://www.onvif.org/ver10/device/wsdl}GetDot1XConfiguration, 
   {http://www.onvif.org/ver10/device/wsdl}GetDot1XConfigurationResponse, 
   {http://www.onvif.org/ver10/device/wsdl}GetDot1XConfigurations, 
   {http://www.onvif.org/ver10/device/wsdl}GetDot1XConfigurationsResponse, 
   {http://www.onvif.org/ver10/device/wsdl}DeleteDot1XConfiguration, 
   {http://www.onvif.org/ver10/device/wsdl}DeleteDot1XConfigurationResponse, 
   {http://www.onvif.org/ver10/device/wsdl}GetRelayOutputs, 
   {http://www.onvif.org/ver10/device/wsdl}GetRelayOutputsResponse, 
   {http://www.onvif.org/ver10/device/wsdl}SetRelayOutputSettings, 
   {http://www.onvif.org/ver10/device/wsdl}SetRelayOutputSettingsResponse, 
   {http://www.onvif.org/ver10/device/wsdl}SetRelayOutputState, 
   {http://www.onvif.org/ver10/device/wsdl}SetRelayOutputStateResponse, 
   {http://www.onvif.org/ver10/device/wsdl}SendAuxiliaryCommand, 
   {http://www.onvif.org/ver10/device/wsdl}SendAuxiliaryCommandResponse, 
   {http://www.onvif.org/ver10/device/wsdl}GetDot11Capabilities, 
   {http://www.onvif.org/ver10/device/wsdl}GetDot11CapabilitiesResponse, 
   {http://www.onvif.org/ver10/device/wsdl}GetDot11Status, 
   {http://www.onvif.org/ver10/device/wsdl}GetDot11StatusResponse, 
   {http://www.onvif.org/ver10/device/wsdl}ScanAvailableDot11Networks, 
   {http://www.onvif.org/ver10/device/wsdl}ScanAvailableDot11NetworksResponse, 
   {http://www.onvif.org/ver10/device/wsdl}GetSystemUris, 
   {http://www.onvif.org/ver10/device/wsdl}GetSystemUrisResponse, 
   {http://www.onvif.org/ver10/device/wsdl}StartFirmwareUpgrade, 
   {http://www.onvif.org/ver10/device/wsdl}StartFirmwareUpgradeResponse, 
   {http://www.onvif.org/ver10/device/wsdl}StartSystemRestore, 
   {http://www.onvif.org/ver10/device/wsdl}StartSystemRestoreResponse
   '''